# Generated by Django 4.2.1 on 2023-06-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gantt_chart", "0002_project_update_percentage_completion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="update_percentage_completion",
            field=models.BooleanField(default=False, verbose_name="Обновлять процент выполнения родительским событиям"),
        ),
    ]
